### ISSUE TITLE
Windows Use

### ISSUE THREAD

**Issue by kleblackford** [vrslev/jack_server#99]
I would like to use this package on Windows. However, when trying to import the package the following error is raised:  

```RuntimeError:` Couldn't find jackserver library```

I suppose this is related to [this issue](https://github.com/jackaudio/jack2/issues/856). Any hints for me attempting to fix this? :)

Thanks

**Comment by kleblackford** [comment]
I will try to compile jack myself. I had JACK 1.9.22 installed and noticed that jackserver.lib is not in the lib folder...

**Comment by vrslev** [comment]
I think, I made it work somehow a year ago, at the time I published the issue you mentioned. Did you try doing what @falkTX suggested here: https://github.com/jackaudio/jack2/issues/856#issuecomment-1070965955?

**Comment by vrslev** [comment]
Previously, `jackserver` library was included in official package. Did something changed?

**Comment by vrslev** [comment]
If it didn’t, we could probably find a way to make `jack_server` work without any hacks on windows consistently after installing JACK

**Comment by kleblackford** [comment]
> Previously, `jackserver` library was included in official package. Did something changed?

No, sorry, I was mistaken. Anyhow, I managed to fix the problem (in an ugly way by adding my JACK2 install path - C:\Program Files\JACK2) to the PATH environment variable.

**Comment by kleblackford** [comment]
> I think, I made it work somehow a year ago, at the time I published the issue you mentioned. Did you try doing what @falkTX suggested here: [jackaudio/jack2#856 (comment)](https://github.com/jackaudio/jack2/issues/856#issuecomment-1070965955)?

Hey, it looks like I have figured how to use winreg to find the JACK install folder. I will have to look into the source code a little deeper to understand how to use this with Windows :)


```{python}
>>> import winreg
>>> 
>>> handle = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
...     r"Software\JACK")
>>>
>>> num_values = winreg.QueryInfoKey(handle)[1]
>>> for i in range(num_values):
...     print(winreg.EnumValue(handle, i))
... 
('ServerExecutable', 'C:\\Program Files\\JACK2\\jackd.exe', 1)
('InstallPath', 'C:\\Program Files\\JACK2', 1)
('Version', 'v1.9.22', 1)
```
